# Generated by Django 4.2 on 2023-05-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_rename_user_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
