# Generated by Django 4.2 on 2023-06-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_message_image_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='flower.webp', upload_to='uploads/'),
        ),
    ]
